export const premiumLandingContent = {
  en: {
    navigation: {
      aria: "Main navigation",
      tagline: "Your smile in trusted hands",
      items: [
        { href: "#leistungen", label: "Services" },
        { href: "#team", label: "Team" },
        { href: "#faq", label: "FAQ" },
        { href: "#standards", label: "Quality" },
        { href: "#kontakt", label: "Contact" },
      ],
      login: "Sign in",
      area: "Portal",
      logout: "Log out",
      profile: "Profile",
      appointmentShort: "Book",
      appointmentLong: "appointment",
      phoneTitle: "0211 1593 482",
      menu: "Menu",
    },
    hero: {
      prototypeLabel: "Concept prototype · not a real dental practice",
      eyebrow: "Dr. Schmidt Dental Practice · Dusseldorf",
      headlineStart: "Precision you can",
      headlineEmphasisOne: "see.",
      headlineMiddle: "Quality you can",
      headlineEmphasisTwo: "feel.",
      pillars: ["Evidence-based", "Transparent", "Calm atmosphere"],
      text: "We create reliable, predictable results through expertise, modern technology and genuine empathy.",
      primaryCta: "Get to know us",
      secondaryCta: "Quality promise",
      note: "We look forward to seeing you.",
      imageAlt: "Modern dental treatment detail",
      badge: "Precision & aesthetics",
    },
    orientation: {
      imageAlt: "Smile Lounge consultation area",
      badgeTitle: "Smile Lounge",
      badgeText: "Consultation & planning",
      eyebrow: "Diagnostics",
      title: "Orientation instead of improvisation",
      text: "Every treatment begins with structured diagnostics based on current guidelines, including precise imaging. You receive a clear assessment, understandable recommendations and real alternatives with transparent benefit-risk evaluation.",
      cards: [
        {
          title: "Hygiene & comfort",
          text: "Hygiene and sterilization protocols based on RKI standards. Low-pain procedures and precisely controlled anesthesia, always as much as needed and as little as possible.",
        },
        {
          title: "Expertise",
          text: "A specialized team with advanced training in restorative dentistry and implantology.",
        },
      ],
    },
    services: {
      eyebrow: "Treatment spectrum",
      title: "Services with clear responsibility",
      text: "Every recommendation is based on a sound diagnosis. No standardized packages, but individual planning with decisions patients can understand.",
      items: [
        {
          title: "Prevention & periodontology",
          text: "Early detection, professional dental cleaning and structured follow-up checks for long-term oral health.",
        },
        {
          title: "Tooth preservation",
          text: "Minimally invasive caries and endodontic treatment, performed precisely and supported by magnification where useful.",
        },
        {
          title: "Implantology",
          text: "Careful planning based on bone structure, with durable restorations designed for biology and function.",
        },
        {
          title: "Aesthetics & function",
          text: "Natural-looking results through the balance of shape, function and aesthetics within one consistent concept.",
        },
        {
          title: "Orthodontics",
          text: "Aligners and fixed appliances, used according to indication with clearly defined treatment goals.",
        },
        {
          title: "Oral surgery",
          text: "Gentle procedures with structured aftercare for safe healing and a lower risk of complications.",
        },
      ],
    },
    team: {
      imageAlt: "The team in the Smile Lounge",
      badgeSmall: "Expert team",
      badgeLarge: "Precision in NRW",
      eyebrow: "Leadership & team spirit",
      title: "Your experts for precision",
      text: "Together with Dr. Maria, we follow a clear vision: structured diagnostics with a high standard of precision and reliability. Every treatment is coordinated as a team to help secure the best possible result for you.",
      leadRole: "Lead dentist",
      leadName: "Dr. Maria Schmidt",
      assistants: [
        {
          name: "Anna",
          role: "Practice management & patient care",
          focus: "Patient support & organization",
        },
        {
          name: "Lena",
          role: "Dental hygiene & prophylaxis",
          focus: "Prevention & bleaching",
        },
        {
          name: "Sophie",
          role: "Dental assistant",
          focus: "Surgical support & hygiene",
        },
      ],
    },
    trustTransition: {
      tickerItems: [
        "DGI IMPLANTOLOGY",
        "MASTER OF SCIENCE",
        "DIGITAL 3D DIAGNOSTICS",
        "CERTIFIED QUALITY",
      ],
      eyebrow: "Expertise & trust",
      titleStart: "Experience that creates",
      titleHighlight: "confidence",
      quote: "Long-standing clinical experience, structured processes and the consistent use of digital procedures form the foundation of our work.",
      stats: [
        { value: "15+", label: "Years of experience", highlight: false },
        { value: "5,000+", label: "Implant restorations", highlight: false },
        { value: "Digitally supported", label: "Planning & execution", highlight: true },
        { value: "Patient satisfaction", label: "Continuously documented", highlight: true },
      ],
    },
    standards: {
      eyebrow: "Safety & quality",
      title: "Scientific standards.",
      subtitle: "Carefully implemented.",
      quote: "We value your feedback. For your safety, however, what matters most are clearly defined, reproducible processes, fully documented and consistently implemented by our team.",
      fieldLabel: "Area:",
      metrics: [
        {
          title: "≥ 125 hours",
          category: "Training",
          detail: "per year on average across the team",
        },
        {
          title: "Class B",
          category: "Hygiene",
          detail: "Steam sterilization with cycle documentation",
        },
        {
          title: "Digital diagnostics",
          category: "X-ray",
          detail: "Modern systems with dose optimization",
        },
        {
          title: "Complete",
          category: "Findings",
          detail: "Audit-proof archiving and transparent documentation",
        },
      ],
      imageAlt: "Hygiene standards and dental instruments",
      badgeSmall: "Validated QM",
      badgeText: "Daily sterilization checks based on RKI guidelines",
      bottomQuote: "Quality management is not a status. It is a continuous process, reviewed, documented and consistently implemented.",
      bottomLabel: "Quality management principle",
    },
    faq: {
      eyebrow: "Patient questions",
      title: "Answers to your questions",
      text: "We value transparent communication. Here you will find initial answers to frequently asked questions. For everything else, we are happy to speak with you personally.",
      items: [
        {
          question: "What does evidence-based dentistry mean?",
          answer: "Evidence-based dentistry means that we select treatment methods based on current clinical studies and scientific evidence, combined with our long-standing experience and your individual needs as a patient.",
        },
        {
          question: "What happens during the first examination?",
          answer: "For your first appointment, we take extra time, usually around 45 to 60 minutes. We carry out comprehensive diagnostics, create digital scans if needed and discuss your wishes and possible treatment options without rushing.",
        },
        {
          question: "Do you treat patients with dental anxiety?",
          answer: "Yes. Caring for anxious patients is one of our key areas. We rely on a calm practice atmosphere, transparent communication about every step and gentle sedation options if desired.",
        },
        {
          question: "What are the benefits of digital impressions?",
          answer: "Instead of traditional silicone impression material, we use modern intraoral scanners. This is more comfortable, helps avoid gagging and provides highly precise 3D data for accurate restorations.",
        },
        {
          question: "How often is professional dental cleaning recommended?",
          answer: "In general, we recommend professional dental cleaning every six months. Depending on your individual oral health or existing periodontal history, shorter intervals of three to four months may be medically useful.",
        },
        {
          question: "Are implant costs covered by statutory health insurance?",
          answer: "Dental implants are usually private services. Statutory health insurance may provide fixed subsidies for dental prosthetics. We prepare a detailed treatment and cost plan for your records in advance.",
        },
        {
          question: "How long do veneers or ceramic crowns last?",
          answer: "Modern ceramic restorations are highly durable. With good home care and regular professional prevention, veneers and crowns can last 10 to 15 years or significantly longer.",
        },
        {
          question: "What should I do in a dental emergency on the weekend?",
          answer: "Outside our opening hours, please contact the official dental emergency service in North Rhine / Dusseldorf. The current emergency practice can be found through the central announcement number 01805 / 98 67 00 or via the Dental Chamber website.",
        },
        {
          question: "Is professional teeth whitening harmful to enamel?",
          answer: "No. Professionally performed in-office bleaching under dental supervision is safe for healthy teeth. We use modern, gentle gels that do not damage enamel but release color pigments.",
        },
        {
          question: "Is the practice wheelchair accessible?",
          answer: "Yes. Our practice rooms are fully accessible. The building entrance, treatment rooms and sanitary facilities are easy to access for patients with limited mobility.",
        },
      ],
    },
    footer: {
      practice: "Dr. Maria Schmidt",
      description: "Dental practice · evidence-based diagnostics and treatment planning at a high medical standard.",
      location: "Location",
      officeHours: "Opening hours",
      weekday: "Mon – Fri",
      break: "Break",
      bookingSmall: "Appointment booking",
      bookingLarge: "REQUEST ONLINE",
      quote: "Dentistry at the highest standard for your natural smile.",
      copyright: "Dental Practice Dr. Maria Schmidt",
      lastUpdated: "Last updated: April 09, 2026",
      legalLabel: "Legal",
      imprint: "Imprint",
      privacy: "Privacy",
    },
    cookie: {
      title: "Cookie consent",
      settingsTitle: "Settings",
      compliance: "GDPR compliance active",
      intro: "We use cookies to provide the best possible service for appointment booking:",
      necessary: "Necessary (patient login & booking)",
      preferences: "Preferences & reach",
      acceptAll: "Accept all",
      necessaryOnly: "Only necessary",
      settingsIntro: "Adjust your privacy settings here:",
      necessaryLabel: "Necessary",
      analysis: "Analytics (opt-in)",
      save: "Save selection",
      cancel: "Cancel",
      privacyLink: "View privacy policy",
    },
    auth: {
      loginTitle: "Sign in",
      loginSubtitle: "Welcome back to your dental practice",
      backTitle: "Back to homepage",
      email: "Email address",
      emailPlaceholder: "you@example.com",
      password: "Password",
      error: "The login details are not correct",
      loading: "Loading...",
      submit: "Sign in now",
      noAccount: "No account yet?",
      register: "Register now",
      authenticating: "Authenticating...",
      checkingAccess: "Checking access...",
    },
  },
  de: {
    navigation: {
      aria: "Hauptnavigation",
      tagline: "Ihr Lächeln in besten Händen",
      items: [
        { href: "#leistungen", label: "Leistungen" },
        { href: "#team", label: "Team" },
        { href: "#faq", label: "FAQ" },
        { href: "#standards", label: "Qualität" },
        { href: "#kontakt", label: "Kontakt" },
      ],
      login: "Anmelden",
      area: "Bereich",
      logout: "Abmelden",
      profile: "Profil",
      appointmentShort: "Termin",
      appointmentLong: "buchen",
      phoneTitle: "0211 1593 482",
      menu: "Menü",
    },
    hero: {
      prototypeLabel: "Konzept-Prototyp · keine echte Zahnarztpraxis",
      eyebrow: "Praxis Dr. Schmidt · Düsseldorf",
      headlineStart: "Präzision, die man",
      headlineEmphasisOne: "sieht.",
      headlineMiddle: "Qualität, die man",
      headlineEmphasisTwo: "fühlt.",
      pillars: ["Evidenzbasiert", "Transparent", "Ruhige Atmosphäre"],
      text: "Wir schaffen für Sie sichere, planbare Ergebnisse durch unsere Expertise, modernste Technik und menschliche Empathie.",
      primaryCta: "Lernen Sie uns kennen",
      secondaryCta: "Qualitätsversprechen",
      note: "Wir freuen uns auf Sie.",
      imageAlt: "Moderne Zahnmedizin Detail",
      badge: "Präzision & Ästhetik",
    },
    orientation: {
      imageAlt: "Smile Lounge - Consultation Area",
      badgeTitle: "Smile Lounge",
      badgeText: "Beratung & Planung",
      eyebrow: "Diagnostik",
      title: "Orientierung statt Improvisation",
      text: "Wir beginnen jede Behandlung mit einer strukturierten Diagnostik nach aktuellen Leitlinien – inklusive präziser Bildgebung. Sie erhalten eine klare Einschätzung, nachvollziehbare Empfehlungen und echte Alternativen mit transparenter Nutzen-Risiko-Abwägung.",
      cards: [
        {
          title: "Hygiene & Komfort",
          text: "Hygiene- und Sterilprotokolle orientiert an RKI-Standards. Schmerzarme Verfahren und präzise gesteuerte Anästhesie – immer so viel wie nötig, so wenig wie möglich.",
        },
        {
          title: "Expertise",
          text: "Ein spezialisiertes Team mit fundierten Weiterbildungen in konservierender Zahnheilkunde und Implantologie.",
        },
      ],
    },
    services: {
      eyebrow: "Spektrum",
      title: "Leistungen mit klarer Verantwortung",
      text: "Wir empfehlen jede Behandlung ausschließlich auf Basis einer fundierten Diagnose. Keine standardisierten Pakete – sondern individuelle Planung mit nachvollziehbaren Entscheidungen.",
      items: [
        {
          title: "Prävention & Parodontologie",
          text: "Früherkennung, professionelle Zahnreinigung und strukturierte Verlaufskontrollen – für langfristige Zahngesundheit.",
        },
        {
          title: "Zahnerhalt",
          text: "Minimalinvasive Karies- und Endodontietherapie – präzise durchgeführt, unterstützt durch Vergrößerungstechniken, wo sinnvoll.",
        },
        {
          title: "Implantologie",
          text: "Sorgfältige Planung auf Basis der Knochensituation – mit langlebigen, biologisch und funktional abgestimmten Versorgungen.",
        },
        {
          title: "Ästhetik & Funktion",
          text: "Natürlich wirkende Ergebnisse durch das Zusammenspiel von Form, Funktion und Ästhetik – in einem konsistenten Gesamtkonzept.",
        },
        {
          title: "Kieferorthopädie",
          text: "Aligner und feste Apparaturen – indikationsgerecht eingesetzt, mit klar definierten Behandlungszielen.",
        },
        {
          title: "Oralchirurgie",
          text: "Schonende Eingriffe mit strukturierter Nachsorge – für eine sichere und möglichst komplikationsarme Heilung.",
        },
      ],
    },
    team: {
      imageAlt: "Das Team in der Smile Lounge",
      badgeSmall: "Expertenteam",
      badgeLarge: "Präzision in NRW",
      eyebrow: "Führung & Teamgeist",
      title: "Ihre Experten für Präzision",
      text: "Gemeinsam mit Dr. Maria leben wir eine klare Vision: Strukturierte Diagnostik mit einem hohen Anspruch an Präzision und Verlässlichkeit. Jede Behandlung wird bei uns im Team koordiniert, um für Sie das bestmögliche Ergebnis zu sichern.",
      leadRole: "Leitende Zahnärztin",
      leadName: "Dr. Maria Schmidt",
      assistants: [
        {
          name: "Anna",
          role: "Praxismanagement & Patient Care",
          focus: "Patientenbetreuung & Organisation",
        },
        {
          name: "Lena",
          role: "Dentalhygiene & Prophylaxe",
          focus: "Prävention & Bleaching",
        },
        {
          name: "Sophie",
          role: "Behandlungsassistenz",
          focus: "Chirurgie-Support & Hygiene",
        },
      ],
    },
    trustTransition: {
      tickerItems: [
        "DGI IMPLANTOLOGIE",
        "MASTER OF SCIENCE",
        "DIGITALE 3D DIAGNOSTIK",
        "ZERTIFIZIERTE QUALITÄT",
      ],
      eyebrow: "Expertise & Vertrauen",
      titleStart: "Erfahrung, die",
      titleHighlight: "Sicherheit schafft",
      quote: "Langjährige klinische Erfahrung, strukturierte Abläufe und der konsequente Einsatz digitaler Verfahren bilden die Grundlage unserer Arbeit.",
      stats: [
        { value: "15+", label: "Jahre Erfahrung", highlight: false },
        { value: "5.000+", label: "Implantatversorgungen", highlight: false },
        { value: "Digital unterstützt", label: "Planung & Umsetzung", highlight: true },
        { value: "Patientenzufriedenheit", label: "Kontinuierlich dokumentiert", highlight: true },
      ],
    },
    standards: {
      eyebrow: "Sicherheit & Qualität",
      title: "Wissenschaftliche Standards.",
      subtitle: "Sorgfältig umgesetzt.",
      quote: "Wir schätzen Ihr Feedback sehr. Entscheidend für Ihre Sicherheit sind bei uns jedoch klar definierte, reproduzierbare Prozesse – von uns lückenlos dokumentiert und konsequent umgesetzt.",
      fieldLabel: "Fachbereich:",
      metrics: [
        {
          title: "≥ 125 Stunden",
          category: "Fortbildung",
          detail: "pro Jahr im Teamdurchschnitt",
        },
        {
          title: "Klasse B",
          category: "Hygiene",
          detail: "Dampfsterilisation mit Zyklenprotokoll",
        },
        {
          title: "Digitale Diagnostik",
          category: "Röntgen",
          detail: "Moderne Systeme mit Dosisoptimierung",
        },
        {
          title: "Lückenlos",
          category: "Befunde",
          detail: "Revisionssicher archiviert & nachvollziehbar",
        },
      ],
      imageAlt: "Hygienestandards & Instrumentarium",
      badgeSmall: "Validiertes QM",
      badgeText: "Tägliche Sterilkontrolle nach RKI-Vorgabe",
      bottomQuote: "Qualitätsmanagement ist kein Zustand, sondern ein kontinuierlicher Prozess – geprüft, dokumentiert und konsequent umgesetzt.",
      bottomLabel: "Leitbild Qualitätsmanagement",
    },
    faq: {
      eyebrow: "Patientenfragen",
      title: "Antworten auf Ihre Fragen",
      text: "Wir legen Wert auf transparente Kommunikation. Hier finden Sie erste Antworten auf häufige Fragen. Für alles weitere stehen wir Ihnen gerne persönlich zur Verfügung.",
      items: [
        {
          question: "Was bedeutet 'evidenzbasierte Zahnmedizin'?",
          answer: "Evidenzbasierte Zahnmedizin bedeutet, dass wir unsere Behandlungsmethoden auf Basis der aktuellsten klinischen Studien und wissenschaftlichen Beweise auswählen, kombiniert mit unserer langjährigen Erfahrung und Ihren individuellen Bedürfnissen als Patient.",
        },
        {
          question: "Wie läuft die erste Untersuchung in Ihrer Praxis ab?",
          answer: "Für Ihren ersten Termin nehmen wir uns besonders viel Zeit (ca. 45-60 Minuten). Wir führen eine umfassende Diagnostik durch, erstellen bei Bedarf digitale Scans und besprechen gemeinsam Ihre Wünsche sowie einen eventuellen Behandlungsplan – ganz ohne Zeitdruck.",
        },
        {
          question: "Bieten Sie Behandlungen für Angstpatienten an?",
          answer: "Ja, die Betreuung von Angstpatienten gehört zu unseren Schwerpunkten. Wir setzen auf eine besonders ruhige Praxisatmosphäre, transparente Kommunikation über jeden Schritt und bieten auf Wunsch auch sanfte Sedierungsmöglichkeiten an.",
        },
        {
          question: "Was sind die Vorteile von digitalen Abdrücken?",
          answer: "Statt klassischer Silikon-Abdruckmasse nutzen wir moderne Intraoralscanner. Das ist nicht nur wesentlich angenehmer und verhindert den Würgereiz, sondern liefert auch hochpräzise 3D-Daten für passgenaue Versorgungen.",
        },
        {
          question: "Wie oft ist eine professionelle Zahnreinigung (PZR) sinnvoll?",
          answer: "In der Regel empfehlen wir eine PZR alle 6 Monate. Je nach individueller Zahngesundheit oder bei bestehender Parodontitis-Vorgeschichte können jedoch auch Intervalle von 3 bis 4 Monaten medizinisch sinnvoll sein.",
        },
        {
          question: "Werden Implantat-Kosten von der Krankenkasse übernommen?",
          answer: "Zahnimplantate sind in der Regel eine Privatleistung, für die gesetzliche Krankenkassen jedoch Festzuschüsse zum Zahnersatz leisten. Wir erstellen Ihnen vorab einen detaillierten Heil- und Kostenplan für Ihre Unterlagen.",
        },
        {
          question: "Wie lange halten Veneers oder Keramikkronen?",
          answer: "Moderne Keramikversorgungen sind extrem langlebig. Bei guter häuslicher Pflege und regelmäßiger professioneller Vorsorge können Veneers und Kronen problemlos 10 bis 15 Jahre oder deutlich länger halten.",
        },
        {
          question: "Was tun bei einem zahnärztlichen Notfall am Wochenende?",
          answer: "Außerhalb unserer Sprechzeiten wenden Sie sich bitte an den offiziellen zahnärztlichen Notdienst Nordrhein / Düsseldorf. Die aktuelle Notdienstpraxis erfahren Sie unter der zentralen Ansagenummer 01805 / 98 67 00 oder auf der Website der Zahnärztekammer Nordrhein.",
        },
        {
          question: "Sind Zahnaufhellungen (Bleaching) schädlich für den Zahnschmelz?",
          answer: "Nein, ein professionell durchgeführtes In-Office-Bleaching unter ärztlicher Aufsicht ist bei gesundem Gebiss unbedenklich. Wir verwenden moderne, schonende Gele, die den Zahnschmelz nicht angreifen, sondern lediglich Farbpigmente lösen.",
        },
        {
          question: "Ist die Praxis barrierefrei zugänglich?",
          answer: "Ja, unsere Praxisräume sind vollständig barrierefrei gestaltet. Sowohl der Zugang zum Gebäude als auch die Behandlungszimmer und sanitären Anlagen sind für Patienten mit eingeschränkter Mobilität problemlos erreichbar.",
        },
      ],
    },
    footer: {
      practice: "Dr. Maria Schmidt",
      description: "Zahnarztpraxis · evidenzbasierte Diagnostik und Therapieplanung auf höchstem medizinischem Niveau.",
      location: "Standort",
      officeHours: "Sprechzeiten",
      weekday: "Mo – Fr",
      break: "Pause",
      bookingSmall: "Terminbuchung",
      bookingLarge: "JETZT ONLINE ANFRAGEN",
      quote: "Zahnmedizin auf höchstem Niveau für Ihr natürliches Lächeln.",
      copyright: "Zahnarztpraxis Dr. Maria Schmidt",
      lastUpdated: "Letzte Aktualisierung: 09. April 2026",
      legalLabel: "Rechtliches",
      imprint: "Impressum",
      privacy: "Datenschutz",
    },
    cookie: {
      title: "Cookie-Zustimmung",
      settingsTitle: "Einstellungen",
      compliance: "DSGVO-Konformität aktiv",
      intro: "Wir nutzen Cookies, um Ihnen den bestmöglichen Service bei der Terminbuchung zu bieten:",
      necessary: "Notwendig (Patienten-Login & Buchung)",
      preferences: "Präferenzen & Reichweite",
      acceptAll: "Alle akzeptieren",
      necessaryOnly: "Nur notwendige",
      settingsIntro: "Passen Sie hier Ihre Privatsphäre-Einstellungen an:",
      necessaryLabel: "Notwendig",
      analysis: "Analyse (Opt-In)",
      save: "Auswahl speichern",
      cancel: "Abbrechen",
      privacyLink: "Datenschutzbestimmungen einsehen",
    },
    auth: {
      loginTitle: "Anmelden",
      loginSubtitle: "Willkommen zurück in Ihrer Zahnarztpraxis",
      backTitle: "Zurück zur Startseite",
      email: "E-Mail-Adresse",
      emailPlaceholder: "ihre@email.de",
      password: "Passwort",
      error: "Anmeldedaten sind nicht korrekt",
      loading: "Wird geladen...",
      submit: "Jetzt anmelden",
      noAccount: "Noch kein Konto?",
      register: "Jetzt registrieren",
      authenticating: "Authentifizierung...",
      checkingAccess: "Prüfe Berechtigung...",
    },
  },
} as const;
